# Generated by Django 4.1.1 on 2023-05-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('self', 'Self')], default='direct', max_length=16),
        ),
    ]
