# Generated by Django 4.1.1 on 2023-05-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_auto_20230415_1725'),
        ('message', '0004_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='first_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_person_chat', to='person.person'),
        ),
        migrations.AddField(
            model_name='chat',
            name='second_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_person_chat', to='person.person'),
        ),
    ]
