# Generated by Django 4.1.1 on 2023-05-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_auto_20230415_1725'),
        ('message', '0005_chat_first_person_chat_second_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='chats', to='person.person'),
        ),
    ]
