version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    build:
      context: backend/
      dockerfile: ./backend.Dockerfile
    container_name: backend
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./logs/
        target: /app/logs/

volumes:
  postgres:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
