# Generated by Django 4.1.1 on 2023-05-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_groupvideo_group_alter_personvideo_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupvideo',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='video_previews'),
        ),
        migrations.AlterField(
            model_name='personvideo',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='video_previews'),
        ),
    ]
