# Generated by Django 4.1.1 on 2022-12-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_remove_person_friends'),
        ('group', '0002_group_long_description_group_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='followers',
            field=models.ManyToManyField(blank=True, to='person.person'),
        ),
        migrations.AddField(
            model_name='group',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.grouptheme'),
        ),
    ]

