# Generated by Django 4.1.1 on 2023-02-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_followers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
