# Generated by Django 4.1.1 on 2022-09-29 03:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_friends_alter_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='submit_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, to='person.person'),
        ),
    ]
