# Generated by Django 4.1.1 on 2022-10-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='person_avatars'),
        ),
    ]
