# Generated by Django 4.1.1 on 2022-11-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
        ('person', '0006_person_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photos',
            field=models.ManyToManyField(blank=True, to='photo.photo'),
        ),
    ]
