# Generated by Django 4.1.1 on 2022-11-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
        ('person', '0007_person_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='persons', to='photo.photo'),
        ),
    ]
