# Generated by Django 4.1.1 on 2022-11-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_remove_person_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='friends',
        ),
    ]
