# Generated by Django 4.1.1 on 2022-11-28 05:37

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_music_song'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='artist_lower_name_idx'),
        ),
    ]
